# Generated by Django 5.0.2 on 2024-03-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlevel',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
